-- AlterEnum
ALTER TYPE "UserRole" ADD VALUE 'RECEPTIONMATE_STAFF';

-- AlterTable
ALTER TABLE "User" ADD COLUMN "branchRoles" JSON NOT NULL DEFAULT '{}' ;
ALTER TABLE "User" ALTER COLUMN "branchRoles" SET DATA TYPE JSONB;
