
import type { Request, Response } from 'express';
import { Router } from 'express';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import readline from 'node:readline';
import { createReadStream } from 'node:fs';
import { access } from 'node:fs/promises';
import { prisma } from '../db.js';

const router = Router();

// DynamoDB client (lazy init to handle missing AWS SDK gracefully)
let dynamoClient: any = null;

const getDynamoClient = () => {
  if (dynamoClient !== null) {
    return dynamoClient;
  }
  
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const { DynamoDBClient, PutItemCommand } = require('@aws-sdk/client-dynamodb');
    const region = process.env.AWS_DEFAULT_REGION || process.env.AWS_REGION || 'eu-west-2';
    dynamoClient = { client: new DynamoDBClient({ region }), PutItemCommand };
    return dynamoClient;
  } catch {
    // AWS SDK not installed or region not configured
    dynamoClient = false;
    return null;
  }
};

const resolveSettingsPath = () => {
  const configuredPath = process.env.BASIC_AGENT_SETTINGS_PATH;
  if (configuredPath && configuredPath.trim().length > 0) {
    return path.resolve(configuredPath);
  }
  return path.resolve(process.cwd(), '../.next/agent/agent_settings.env');
};

const settingsPath = resolveSettingsPath();
const knowledgePath = path.resolve(path.dirname(settingsPath), 'agent_knowledge.json');

const ensureSecretIsValid = (req: Request) => {
  const requiredSecret = process.env.AGENT_CONFIG_WEBHOOK_SECRET;
  if (!requiredSecret) {
    return true;
  }

  const providedSecret = req.headers['x-agent-config-secret'];
  if (Array.isArray(providedSecret)) {
    return providedSecret.includes(requiredSecret);
  }
  return providedSecret === requiredSecret;
};

router.post('/agent-config', async (req: Request, res: Response) => {
  if (!ensureSecretIsValid(req)) {
    return res.status(401).json({ error: 'Unauthorized' });
  }

  const { garageId, configuration, knowledgeBase, knowledgeVersion } = req.body ?? {};

  if (!garageId || typeof configuration !== 'object' || configuration === null) {
    return res.status(400).json({ error: 'Invalid payload' });
  }

  const sanitizedKnowledge = Array.isArray(knowledgeBase)
    ? knowledgeBase
        .map((entry: Record<string, unknown>) => {
          const content = typeof entry?.content === 'string' ? entry.content.trim() : '';
          if (!content) {
            return null;
          }
          return {
            id: typeof entry?.id === 'string' ? entry.id : undefined,
            title: typeof entry?.title === 'string' && entry.title.trim() ? entry.title.trim() : null,
            source: typeof entry?.source === 'string' ? entry.source : 'website-scan',
            url: typeof entry?.url === 'string' ? entry.url : null,
            content,
            metadata: typeof entry?.metadata === 'object' && entry.metadata !== null ? entry.metadata : null,
            createdAt: typeof entry?.createdAt === 'string' ? entry.createdAt : null,
            updatedAt: typeof entry?.updatedAt === 'string' ? entry.updatedAt : null,
          };
        })
        .filter((entry): entry is {
          id: string | undefined;
          title: string | null;
          source: string;
          url: string | null;
          content: string;
          metadata: Record<string, unknown> | null;
          createdAt: string | null;
          updatedAt: string | null;
        } => Boolean(entry))
    : [];

  const resolvedKnowledgeVersion =
    typeof knowledgeVersion === 'string' && knowledgeVersion.trim()
      ? knowledgeVersion.trim()
      : sanitizedKnowledge.reduce<string | null>((latest, entry) => {
          const timestamp = entry.updatedAt || entry.createdAt;
          if (!timestamp) {
            return latest;
          }
          if (!latest) {
            return timestamp;
          }
          return timestamp > latest ? timestamp : latest;
        }, null) ?? '';

  const formatEnvValue = (value: unknown) => {
    if (value === null || value === undefined) {
      return '';
    }
    const stringValue = String(value);
    if (!stringValue) {
      return '';
    }
    if (/[\n\r]/.test(stringValue)) {
      return JSON.stringify(stringValue);
    }
    if (/[\s#]/.test(stringValue)) {
      return JSON.stringify(stringValue).slice(1, -1);
    }
    return stringValue;
  };

  const envLines = [
    '# Auto-generated by portal webhook. Manual edits will be overwritten.',
    `UPDATED_AT=${new Date().toISOString()}`,
    `GARAGE_ID=${formatEnvValue(garageId)}`,
    `AGENT_BRANCH_NAME=${formatEnvValue(configuration.branchName)}`,
    `AGENT_PHONE_NUMBER=${formatEnvValue(configuration.phoneNumber)}`,
    `AGENT_EMAIL_ADDRESS=${formatEnvValue(configuration.emailAddress)}`,
    `AGENT_WEBSITE_URL=${formatEnvValue(configuration.websiteUrl)}`,
    `AGENT_GREETING_LINE=${formatEnvValue(configuration.greetingLine)}`,
    `AGENT_TONE_PREFERENCE=${formatEnvValue(configuration.tonePreference)}`,
    `AGENT_RESPONSE_SPEED=${formatEnvValue(configuration.responseSpeed || 'normal')}`,
    `AGENT_INTERRUPTION_SENSITIVITY=${formatEnvValue(
      typeof configuration.interruptionSensitivity === 'number'
        ? configuration.interruptionSensitivity.toFixed(2)
        : '0.5',
    )}`,
    `AGENT_ALLOW_FAST_FIT_ONLY=${configuration.allowFastFitOnly ? 'true' : 'false'}`,
    `AGENT_ENABLE_SMS_BOOKING_LINKS=${configuration.enableSmsBookingLinks !== false ? 'true' : 'false'}`,
    `AGENT_HOLIDAY_CLOSURES=${formatEnvValue(configuration.holidayClosures)}`,
    `AGENT_WEEKLY_OPENING_HOURS=${formatEnvValue(JSON.stringify(configuration.weeklyOpeningHours ?? {}))}`,
    `AGENT_KNOWLEDGE_VERSION=${formatEnvValue(resolvedKnowledgeVersion)}`,
    `GH_CUSTOMER_ID=${formatEnvValue(configuration.garageHiveSettings?.customerId || '')}`,
    `GH_LOCATION_ID=${formatEnvValue(configuration.garageHiveSettings?.locationId || '')}`,
  ];

  try {
    await fs.mkdir(path.dirname(settingsPath), { recursive: true });
    await fs.writeFile(`${settingsPath}`, `${envLines.join('\n')}\n`, 'utf8');

    if (sanitizedKnowledge.length > 0) {
      const knowledgePayload = {
        updatedAt: resolvedKnowledgeVersion || new Date().toISOString(),
        documents: sanitizedKnowledge,
      };
      await fs.writeFile(knowledgePath, `${JSON.stringify(knowledgePayload, null, 2)}\n`, 'utf8');
    } else {
      await fs.rm(knowledgePath, { force: true });
    }

    // Also update DynamoDB if available
    const dynamo = getDynamoClient();
    if (dynamo) {
      try {
        await dynamo.client.send(new dynamo.PutItemCommand({
          TableName: 'AgentConfig',
          Item: {
            garageId: { S: garageId },
            updatedAt: { S: new Date().toISOString() },
            configuration: { S: JSON.stringify(configuration) },
            knowledgeBase: { S: JSON.stringify(sanitizedKnowledge) },
            knowledgeVersion: resolvedKnowledgeVersion
              ? { S: resolvedKnowledgeVersion }
              : { NULL: true },
          },
        }));
      } catch (dynamoError) {
        if (process.env.NODE_ENV !== 'production') {
          // eslint-disable-next-line no-console
          console.error('Failed to update DynamoDB (continuing anyway)', dynamoError);
        }
      }
    }
  } catch (error) {
    if (process.env.NODE_ENV !== 'production') {
      // eslint-disable-next-line no-console
      console.error('Failed to persist agent configuration', error);
    }
    return res.status(500).json({ error: 'Failed to persist configuration' });
  }

  return res.status(204).send();
});

const SFTP_BASE = process.env.SFTP_UPLOAD_BASE_PATH || '/home/tyresoft-uploads/uploads';

const slugifyBranchName = (name: string) =>
  name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');

const parseCsvLine = (line: string): string[] => {
  const result: string[] = [];
  let current = '';
  let inQuotes = false;
  for (const char of line) {
    if (char === '"') {
      inQuotes = !inQuotes;
    } else if (char === ',' && !inQuotes) {
      result.push(current);
      current = '';
    } else {
      current += char;
    }
  }
  result.push(current);
  return result;
};

const readCsvAsRecords = (filePath: string): Promise<Record<string, string>[]> =>
  new Promise((resolve, reject) => {
    const rows: Record<string, string>[] = [];
    let headers: string[] = [];
    let lineNum = 0;
    const rl = readline.createInterface({
      input: createReadStream(filePath, { encoding: 'utf8' }),
      crlfDelay: Infinity,
    });
    rl.on('line', (line) => {
      const fields = parseCsvLine(line);
      if (lineNum === 0) {
        headers = fields.map((h) => h.trim());
      } else if (line.trim()) {
        const row: Record<string, string> = {};
        headers.forEach((h, i) => { row[h] = fields[i]?.trim() ?? ''; });
        rows.push(row);
      }
      lineNum++;
    });
    rl.on('close', () => resolve(rows));
    rl.on('error', reject);
  });

router.get('/tyre-inventory/:garageId', async (req: Request, res: Response) => {
  if (!ensureSecretIsValid(req)) {
    return res.status(401).json({ error: 'Unauthorized' });
  }

  const { garageId } = req.params;
  const branchNum = req.query.branch === '2' ? 2 : 1;

  const config = await prisma.agentConfiguration.findUnique({
    where: { garageId },
    select: { branchName: true },
  });

  if (!config) {
    return res.status(404).json({ error: 'Garage not found' });
  }

  const folder = slugifyBranchName(config.branchName);
  const csvPath = path.join(SFTP_BASE, folder, `Products Branch ${branchNum}.csv`);

  try {
    await access(csvPath);
  } catch {
    return res.status(404).json({ error: 'No inventory file found', folder });
  }

  try {
    const rows = await readCsvAsRecords(csvPath);
    const inventory = rows.map((row) => ({
      stock_number: row['Product Stock Number'] ?? '',
      ean: row['Product EAN'] ?? '',
      title: row['Product Title'] ?? '',
      price: parseFloat(row['Retail'] || '0') || 0,
      width: row['Width'] ?? '',
      aspect_ratio: row['Aspect Ratio'] ?? '',
      rim: row['Rim'] ?? '',
      speed_rating: row['Speed Rating'] ?? '',
      load_index: row['Load Index'] ?? '',
      brand: row['Brand Name'] ?? '',
      vehicle_type: row['Vehicle Type'] ?? '',
      product_type: row['Product Type'] ?? '',
      runflat: (row['Runflat'] ?? 'FALSE').toUpperCase() === 'TRUE',
      availability: row['Product Channel Available'] ?? '',
      lead_time: row['Product Channel Lead Time'] ?? '',
      source_supplier_id: parseInt(row['Product Channel Source Supplier ID'] || '0', 10) || 0,
    }));

    console.log(`[TYRE_INVENTORY] Serving ${inventory.length} tyres for garage ${garageId} branch ${branchNum} (folder: ${folder})`);
    return res.json({ branch: branchNum, count: inventory.length, inventory });
  } catch (error) {
    console.error('[TYRE_INVENTORY] Failed to read CSV:', error);
    return res.status(500).json({ error: 'Failed to read inventory file' });
  }
});

export default router;
