
import type { Request, Response } from 'express';
import { Router } from 'express';
import { promises as fs } from 'node:fs';
import path from 'node:path';

const router = Router();

const resolveSettingsPath = () => {
  const configuredPath = process.env.BASIC_AGENT_SETTINGS_PATH;
  if (configuredPath && configuredPath.trim().length > 0) {
    return path.resolve(configuredPath);
  }
  return path.resolve(process.cwd(), '../.next/agent/agent_settings.env');
};

const settingsPath = resolveSettingsPath();
const knowledgePath = path.resolve(path.dirname(settingsPath), 'agent_knowledge.json');

const ensureSecretIsValid = (req: Request) => {
  const requiredSecret = process.env.AGENT_CONFIG_WEBHOOK_SECRET;
  if (!requiredSecret) {
    return true;
  }

  const providedSecret = req.headers['x-agent-config-secret'];
  if (Array.isArray(providedSecret)) {
    return providedSecret.includes(requiredSecret);
  }
  return providedSecret === requiredSecret;
};

router.post('/agent-config', async (req: Request, res: Response) => {
  if (!ensureSecretIsValid(req)) {
    return res.status(401).json({ error: 'Unauthorized' });
  }

  const { garageId, configuration, knowledgeBase, knowledgeVersion } = req.body ?? {};

  if (!garageId || typeof configuration !== 'object' || configuration === null) {
    return res.status(400).json({ error: 'Invalid payload' });
  }

  const sanitizedKnowledge = Array.isArray(knowledgeBase)
    ? knowledgeBase
        .map((entry: Record<string, unknown>) => {
          const content = typeof entry?.content === 'string' ? entry.content.trim() : '';
          if (!content) {
            return null;
          }
          return {
            id: typeof entry?.id === 'string' ? entry.id : undefined,
            title: typeof entry?.title === 'string' && entry.title.trim() ? entry.title.trim() : null,
            source: typeof entry?.source === 'string' ? entry.source : 'website-scan',
            url: typeof entry?.url === 'string' ? entry.url : null,
            content,
            metadata: typeof entry?.metadata === 'object' && entry.metadata !== null ? entry.metadata : null,
            createdAt: typeof entry?.createdAt === 'string' ? entry.createdAt : null,
            updatedAt: typeof entry?.updatedAt === 'string' ? entry.updatedAt : null,
          };
        })
        .filter((entry): entry is {
          id: string | undefined;
          title: string | null;
          source: string;
          url: string | null;
          content: string;
          metadata: Record<string, unknown> | null;
          createdAt: string | null;
          updatedAt: string | null;
        } => Boolean(entry))
    : [];

  const resolvedKnowledgeVersion =
    typeof knowledgeVersion === 'string' && knowledgeVersion.trim()
      ? knowledgeVersion.trim()
      : sanitizedKnowledge.reduce<string | null>((latest, entry) => {
          const timestamp = entry.updatedAt || entry.createdAt;
          if (!timestamp) {
            return latest;
          }
          if (!latest) {
            return timestamp;
          }
          return timestamp > latest ? timestamp : latest;
        }, null) ?? '';

  const formatEnvValue = (value: unknown) => {
    if (value === null || value === undefined) {
      return '';
    }
    const stringValue = String(value);
    if (!stringValue) {
      return '';
    }
    if (/[\n\r]/.test(stringValue)) {
      return JSON.stringify(stringValue);
    }
    if (/[\s#]/.test(stringValue)) {
      return JSON.stringify(stringValue).slice(1, -1);
    }
    return stringValue;
  };

  const envLines = [
    '# Auto-generated by portal webhook. Manual edits will be overwritten.',
    `UPDATED_AT=${new Date().toISOString()}`,
    `GARAGE_ID=${formatEnvValue(garageId)}`,
    `AGENT_BRANCH_NAME=${formatEnvValue(configuration.branchName)}`,
    `AGENT_PHONE_NUMBER=${formatEnvValue(configuration.phoneNumber)}`,
    `AGENT_EMAIL_ADDRESS=${formatEnvValue(configuration.emailAddress)}`,
    `AGENT_WEBSITE_URL=${formatEnvValue(configuration.websiteUrl)}`,
    `AGENT_GREETING_LINE=${formatEnvValue(configuration.greetingLine)}`,
    `AGENT_TONE_PREFERENCE=${formatEnvValue(configuration.tonePreference)}`,
    `AGENT_RESPONSE_SPEED=${formatEnvValue(configuration.responseSpeed || 'normal')}`,
    `AGENT_INTERRUPTION_SENSITIVITY=${formatEnvValue(
      typeof configuration.interruptionSensitivity === 'number'
        ? configuration.interruptionSensitivity.toFixed(2)
        : '0.5',
    )}`,
    `AGENT_ALLOW_FAST_FIT_ONLY=${configuration.allowFastFitOnly ? 'true' : 'false'}`,
    `AGENT_CALL_SUMMARY_EMAIL=${formatEnvValue(configuration.callSummaryEmail)}`,
    `AGENT_HOLIDAY_CLOSURES=${formatEnvValue(configuration.holidayClosures)}`,
    `AGENT_WEEKLY_OPENING_HOURS=${formatEnvValue(JSON.stringify(configuration.weeklyOpeningHours ?? {}))}`,
    `AGENT_KNOWLEDGE_VERSION=${formatEnvValue(resolvedKnowledgeVersion)}`,
    `GH_CUSTOMER_ID=${formatEnvValue(configuration.garageHiveSettings?.customerId || '')}`,
    `GH_LOCATION_ID=${formatEnvValue(configuration.garageHiveSettings?.locationId || '')}`,
  ];

  try {
    await fs.mkdir(path.dirname(settingsPath), { recursive: true });
    await fs.writeFile(`${settingsPath}`, `${envLines.join('\n')}\n`, 'utf8');

    if (sanitizedKnowledge.length > 0) {
      const knowledgePayload = {
        updatedAt: resolvedKnowledgeVersion || new Date().toISOString(),
        documents: sanitizedKnowledge,
      };
      await fs.writeFile(knowledgePath, `${JSON.stringify(knowledgePayload, null, 2)}\n`, 'utf8');
    } else {
      await fs.rm(knowledgePath, { force: true });
    }
  } catch (error) {
    if (process.env.NODE_ENV !== 'production') {
      // eslint-disable-next-line no-console
      console.error('Failed to persist agent configuration', error);
    }
    return res.status(500).json({ error: 'Failed to persist configuration' });
  }

  return res.status(204).send();
});

export default router;
